# 本番環境
production:
  password: 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
  theme_id: "126179573933"
  store: https://scm-gittest.myshopify.com


# 開発環境
development:
  password: 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
  theme_id: "126205362349"
  store: https://scm-gittest.myshopify.com